-- AUTO-GENERATED FILE. DO NOT EDIT.
-- Generated by ops/scripts/gen_pg_schema.py

-- source: src/backend/declarations/notes.py:8
CREATE TABLE IF NOT EXISTS "public"."note" (
  "id" JSONB PRIMARY KEY NOT NULL,
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "created_at" TEXT NOT NULL
);

-- source: src/backend/declarations/notes.py:16
CREATE TABLE IF NOT EXISTS "public"."notebook" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "note_id" JSONB NOT NULL
);
